Done?????????????????????????????????????????????

diff --git a/project_files/project2/cordic/HLS/cordic/Makefile b/project_files/project2/cordic/HLS/cordic/Makefile
--- a/project_files/project2/cordic/HLS/cordic/Makefile
+++ b/project_files/project2/cordic/HLS/cordic/Makefile
@@ -93,6 +93,18 @@ run: clean test hls report
 run2: hls report
 
 
+$(CURDIR)/export_$(TOP).tcl:
+	@{ \
+        echo "open_component $(TOP).comp"; \
+        echo "export_design -format ip_catalog -rtl verilog -version 1.0 -ipname $(TOP)"; \
+        echo "exit"; \
+    } > $(CURDIR)/export_$(TOP).tcl
+
+
+ip: hls $(CURDIR)/export_$(TOP).tcl
+	$(HLS_COMPILER) $(CURDIR)/export_$(TOP).tcl || { s=$$?; echo "$(HLS_COMPILER) -source $(CURDIR)/export_$(TOP).tcl failed $$s" >&2; exit $$s; }
+
+
 .PHONY: clean hls test report
 
 # Prevent make from deleting the .bin intermediate files
