Pynq update (#43)
* Updated lab 1

* Revise design import instructions for Vitis HLS

Updated instructions for importing designs to reflect changes from Vivado HLS to Vitis HLS.

* Fix image directive formatting in PYNQ example

diff --git a/project_files/lab1/Makefile b/project_files/lab1/Makefile
--- a/project_files/lab1/Makefile
+++ b/project_files/lab1/Makefile
@@ -3,16 +3,26 @@
 # 
 #
 
-# ---------- Set top function name here ----------------
+# select the HLS compiler to use (vivado_hls or vitis)
 TOP = mul
 # -------------------------------------------------------
 
 USE_VITIS=1
 
 ifeq ($(USE_VITIS),1)
-VITIS_COMPILER := $(shell dirname $(shell which vitis_hls))
 
-VHLS = $(VITIS_COMPILER)/../../Vitis_HLS/2024.1
+VITIS_HLS_PATH := $(shell which vitis_hls 2>/dev/null)
+ifeq ($(strip $(VITIS_HLS_PATH)),)
+  $(error Could not find "vitis_hls" on PATH.)
+endif
+VITIS_COMPILER := $(shell dirname "$(VITIS_HLS_PATH)")
+
+ifneq (,$(findstring 2024.2,$(VITIS_HLS_PATH)))
+  VHLS := $(VITIS_COMPILER)/../../Vitis/2024.2
+else
+  VHLS := $(VITIS_COMPILER)/../../Vitis_HLS/2024.1
+endif
+
 HLS_COMPILER=vitis-run --mode hls --tcl 
 else
 VHLS := $(shell vivado_hls -r)
@@ -76,11 +86,21 @@ test: $(EXAMPLES_LOG)
 report: hls
 	cp -f $(TOP).comp/hls/syn/report/$(TOP)_csynth.rpt $(CURDIR) || true
 
+$(CURDIR)/export_$(TOP).tcl:
+	@{ \
+	    echo "open_component $(TOP).comp"; \
+		echo "export_design -format ip_catalog -rtl verilog -version 1.0 -ipname mul "; \
+		echo "exit"; \
+	} > $(CURDIR)/export_$(TOP).tcl
+
+
+ip: hls $(CURDIR)/export_$(TOP).tcl
+	$(HLS_COMPILER) $(CURDIR)/export_$(TOP).tcl || { s=$$?; echo "$(HLS_COMPILER) -source $(CURDIR)/export_$(TOP).tcl failed $$s" >&2; exit $$s; }
 
 clean:
-	rm -rf *.o *.log *.bin *.tcl *.comp *.rpt logs hls out.dat
+	rm -rf *.o *.log *.bin *.tcl *.comp *.rpt logs hls out.dat *.jou
 
-.PHONY: clean hls test report
+.PHONY: clean hls test report ip
 
 # Prevent make from deleting the .bin intermediate files
 .PRECIOUS: %.bin %.tcl 
